language: c
sudo: required
env:
  global:
    - MAKEFLAGS="-j 5"

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      env:
        - MATRIX_EVAL="CC=gcc-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6-base
      env:
        - MATRIX_EVAL="CC=gcc-6"

before_install:
  - export PLX_SDK_DIR=$PWD

script:
  - make all
